### ISSUE TITLE
scx_lavd: last_consume_clk should be update when enqueue a first task to dsq

### ISSUE THREAD

**Issue by archerbroler** [sched-ext/scx#1003]
In consume_starving_task, last_consume_clk + LAVD_CPDOM_STARV_NS will be the test case for starving dsq.
But if short before this, a task is enqueued into the empty dsq. The  consume_starving_task test case will use the last last_consume_clk time which happens long ago.
This will cause the new enqueued task be consumed fast because of a starving dsq.
I think this empty to first task dsq should not be considered as starving. So, maybe last_consume_clk should be updated when enqueue a task to an empty dsq?

**Comment by multics69** [comment]
consume_starving_task() was dropped with https://github.com/sched-ext/scx/pull/1000
