### ISSUE TITLE
scx: include kernel version in bpf dumps

### ISSUE THREAD

**Issue by likewhatevs** [sched-ext/scx#1009]
Include kernel version in bpf dumps.

This can be done in each scheduler, but I'm wondering if we should see if this could be added to libbpf (i.e. when dumps happen, we only print what libbpf prints).

This will help w/ debugging verifier failures that only occur on specific kernel versions.

**Comment by hodgesds** [comment]
Maybe we can have a wrapper that reads `extern int LINUX_KERNEL_VERSION __kconfig;` and any other kernel/scheduler configs in a common format.

**Comment by hodgesds** [comment]
I think this can be closed for now, `scx_layered` is the only (rust) scheduler that has a `dump` implementation.
