### ISSUE TITLE
scx_lavd: stopping_tm_est_ns should be updated when dispatch prev

### ISSUE THREAD

**Issue by archerbroler** [sched-ext/scx#1043]
When dispatch prev which in enqueued, LAVD recal its slice, this is great.
But, I think the cpuc->stopping_tm_est_ns should be recal too.
A task keep running for next slice with CPU's old stopping_tm_est_ns will cause that CPU not easy preempted as it should be.

**Comment by multics69** [comment]
I think we don't need because stopping_tm_est_ns will be calculated when ops..running() is called.

**Comment by archerbroler** [comment]
yes, you are right. Sorry for my mistake.

**Comment by multics69** [comment]
No problem. Thank you for the good questions!
