### ISSUE TITLE
scx_lavd: lat_cri in comp_preemption_info may vary too little

### ISSUE THREAD

**Issue by archerbroler** [sched-ext/scx#1053]
If a process launch multiple threads run same logic, the lat_cri calculated for these sam logic threads is close to each other.  And they are dynamic. Assuming three thread with same logic, lat_cri will change from 321,322,323 to 322,321,323 for example. Which make the comp_preemption_info test pass or not in not intended way.
Maybe lat_cri compare in comp_preemption_info need a 10% tolerance?

**Comment by multics69** [comment]
Thank you for the good suggestion. It sounds making sense. I will think about a bit further the implications of changes. BTW, do you have any benchmark belonging to the scenario you mentioned?

**Comment by archerbroler** [comment]
schbench maybe what you need

**Comment by multics69** [comment]
Can you share the exact command line for schbench?

**Comment by archerbroler** [comment]
I think default schbech cmd will launch cpu num threads.
schbench may have rps impact, maybe dhrystone match the most？

**Comment by multics69** [comment]
I have tested 5-10% tolerance, but there were no measurable differences. Let's keep it as it is to make thing simple.
