### ISSUE TITLE
Build fails when compiling lib.bpf.o (with fetched bpftool)

### ISSUE THREAD

**Issue by JohnRTitor** [sched-ext/scx#1068]
## Steps to reproduce

- Clone the latest 1.0.7 tag, or you can clone [my nixpkgs branch](https://github.com/JohnRTitor/nixpkgs/tree/scx-package) (https://github.com/JohnRTitor/nixpkgs/commit/413f9c254717baf7c6be968f1c0707e8ee1c7659)
- Build the package, if using nix just use `nix build .#scx.cscheds`.
- See the build failed

### Relevant log
```log
scx_cscheds> [14/49] Generating lib/lib with a custom command
scx_cscheds> FAILED: lib/lib.bpf.o 
scx_cscheds> /build/source/meson-scripts/compile_scx_lib /build/source/build/bpftool/src/bpftool lib/lib.bpf.o lib lib/sdt_task.bpf.o
scx_cscheds> /build/source/meson-scripts/compile_scx_lib: line 12: bpftool: command not found
scx_cscheds> [15/49] Generating 'scheds/c/scx_flatcg.p/scx_flatcg.bpf.o'
scx_cscheds> clang: warning: argument unused during compilation: '--gcc-toolchain=/nix/store/4krab2h0hd4wvxxmscxrw21pl77j4i7j-gcc-13.3.0' [-Wunused-command-line-argument]
```

Full log: https://termbin.com/mf77 / https://pastebin.com/MLzN6KcY

## Possible reasons

As can I see https://github.com/sched-ext/scx/blob/fefe29b7fb9331a6741a418b9272b97762d7b42e/meson.build#L190-L199
It does not build bpftool_exe if we ask it to fetch bpftool.

But we still need `bpftool_exe` to build the gen_bpf_skel.
https://github.com/sched-ext/scx/blob/fefe29b7fb9331a6741a418b9272b97762d7b42e/meson.build#L282

(PS: I am not much familiar with Meson, so if this is wrong, please go easy on me!)

CC @PedroHLC @JakeHillion

**Comment by likewhatevs** [comment]
This seems accurate -- kind of wonder if we ought to just have bpftool handled by "have bpftool available on your system".

**Comment by JohnRTitor** [comment]
Fixed by https://github.com/sched-ext/scx/pull/1071.

I cherry-picked the other patches too to fix merge conflict.

https://github.com/sched-ext/scx/commit/22d45e6ddbea81efc17a91ca6d713a7e396cea52

https://github.com/sched-ext/scx/commit/a72c24e7e5670b4533c4508d6d6c980d8487cb50

https://github.com/sched-ext/scx/commit/21cf3ccd1d263cf7aac3afe337911f18ba329dca
