### ISSUE TITLE
ninja: error: 'scheds/c/lib.bpf.o', needed by 'scheds/c/scx_simple.p/lib.bpf.skel.h', missing and no known rule to make it

### ISSUE THREAD

**Issue by chyokan** [sched-ext/scx#1120]
root@VMware-Virtual-Platform:~/sched_ext/scx# meson setup --reconfigure build
The Meson build system
Version: 1.3.2
Source dir: /root/sched_ext/scx
Build dir: /root/sched_ext/scx/build
Build type: native build
Project name: sched_ext schedulers
Project version: 1.0.8
C compiler for the host machine: cc (gcc 13.3.0 "cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0")
C linker for the host machine: cc ld.bfd 2.42
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program clang found: YES (/usr/bin/clang)
Program /root/sched_ext/scx/meson-scripts/veristat found: YES (/root/sched_ext/scx/meson-scripts/veristat)
Program /root/sched_ext/scx/meson-scripts/veristat_diff found: YES (/root/sched_ext/scx/meson-scripts/veristat_diff)
Program /root/sched_ext/scx/meson-scripts/run_stress_tests found: YES (/root/sched_ext/scx/meson-scripts/run_stress_tests)
Program /root/sched_ext/scx/meson-scripts/get_clang_ver found: YES (/root/sched_ext/scx/meson-scripts/get_clang_ver)
Program /root/sched_ext/scx/meson-scripts/get_bpftool_ver found: YES (/root/sched_ext/scx/meson-scripts/get_bpftool_ver)
Program /root/sched_ext/scx/meson-scripts/bpftool_build_skel found: YES (/root/sched_ext/scx/meson-scripts/bpftool_build_skel)
Program /root/sched_ext/scx/meson-scripts/get_sys_incls found: YES (/root/sched_ext/scx/meson-scripts/get_sys_incls)
Program /root/sched_ext/scx/meson-scripts/test_sched found: YES (/root/sched_ext/scx/meson-scripts/test_sched)
Program /root/sched_ext/scx/meson-scripts/fetch_libbpf found: YES (/bin/bash /root/sched_ext/scx/meson-scripts/fetch_libbpf)
Program /root/sched_ext/scx/meson-scripts/build_libbpf found: YES (/root/sched_ext/scx/meson-scripts/build_libbpf)
Program /root/sched_ext/scx/meson-scripts/fetch_bpftool found: YES (/bin/bash /root/sched_ext/scx/meson-scripts/fetch_bpftool)
Program /root/sched_ext/scx/meson-scripts/build_bpftool found: YES (/bin/bash /root/sched_ext/scx/meson-scripts/build_bpftool)
Program /root/sched_ext/scx/meson-scripts/compile_scx_lib found: YES (/root/sched_ext/scx/meson-scripts/compile_scx_lib)
Program jq found: YES (/usr/bin/jq)
Program make found: YES (/usr/bin/make)
Program nproc found: YES (/usr/bin/nproc)
Message: Fetching libbpf repo
Library elf found: YES
Library z found: YES
Library zstd found: YES
Message: Fetching bpftool repo
Message: cpu=x86_64 bpf_base_cflags=['-g', '-O2', '-Wall', '-Wno-compare-distinct-pointer-types', '-D__TARGET_ARCH_x86', '-mcpu=v3', '-mlittle-endian', '-idirafter /usr/lib/llvm-18/lib/clang/18/include', '-idirafter /usr/local/include', '-idirafter /usr/include/x86_64-linux-gnu', '-idirafter /usr/include']
Program cargo found: YES (/usr/bin/cargo)
Program /root/sched_ext/scx/meson-scripts/cargo_fetch found: YES (/root/sched_ext/scx/meson-scripts/cargo_fetch)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency systemd found: YES 255 (cached)
Dependency openrc found: YES 0.55 (cached)
Found pkg-config: YES (/usr/bin/pkg-config) 1.8.1
Found CMake: /usr/bin/cmake (3.28.3)
Run-time dependency libalpm found: NO (tried pkgconfig and cmake)
Build targets in project: 59

sched_ext schedulers 1.0.8

  User defined options
    prefix: /root

Found ninja-1.11.1 at /usr/bin/ninja
Cleaning... 0 files.
root@VMware-Virtual-Platform:~/sched_ext/scx# meson compile -C build/
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /root/sched_ext/scx/build
ninja: Entering directory `/root/sched_ext/scx/build'
ninja: error: 'scheds/c/lib.bpf.o', needed by 'scheds/c/scx_simple.p/lib.bpf.skel.h', missing and no known rule to make it
root@VMware-Virtual-Platform:~/sched_ext/scx# 
root@VMware-Virtual-Platform:~/sched_ext/scx# 
root@VMware-Virtual-Platform:~/sched_ext/scx# 
root@VMware-Virtual-Platform:~/sched_ext/scx# meson install -C build/
ninja: Entering directory `/root/sched_ext/scx/build'
ninja: error: 'scheds/c/lib.bpf.o', needed by 'scheds/c/scx_simple.p/lib.bpf.skel.h', missing and no known rule to make it
Could not rebuild /root/sched_ext/scx/build

Could someone please help me solve this problem?

**Comment by pingxiang-chen** [comment]
Same issue here.

**Comment by etsal** [comment]
Thank you for the report. Could you try the following:

- Can you run ```meson compile -C build/ scx_sdt```?
- Similarly, can you run ```meson compile -C build/ scx_flatcg```?
- Can you run ```meson compile -C build```? This will build all of the schedulers.

Please delete ```build```  and do ```meson setup``` before running each of the commands.

- Can you run bpftool -V?
- Can you post the git hash of the scx version you are using?

**Comment by kmikita** [comment]
@chyokan update meson to latest then reconfigure.

**Comment by pingxiang-chen** [comment]
@etsal 

Here is what I tried:

```console
shawn@shawn-mini-desktop:~/workspace/scx-1.0.8$ meson setup build --prefix ~
The Meson build system
Version: 1.3.2
Source dir: /home/shawn/workspace/scx-1.0.8
Build dir: /home/shawn/workspace/scx-1.0.8/build
Build type: native build
Project name: sched_ext schedulers
Project version: 1.0.8
C compiler for the host machine: cc (gcc 13.3.0 "cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0")
C linker for the host machine: cc ld.bfd 2.42
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program clang found: YES (/usr/bin/clang)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/veristat found: YES (/home/shawn/workspace/scx-1.0.8/meson-scripts/veristat)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/veristat_diff found: YES (/home/shawn/workspace/scx-1.0.8/meson-scripts/veristat_diff)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/run_stress_tests found: YES (/home/shawn/workspace/scx-1.0.8/meson-scripts/run_stress_tests)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/get_clang_ver found: YES (/home/shawn/workspace/scx-1.0.8/meson-scripts/get_clang_ver)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/get_bpftool_ver found: YES (/home/shawn/workspace/scx-1.0.8/meson-scripts/get_bpftool_ver)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/bpftool_build_skel found: YES (/home/shawn/workspace/scx-1.0.8/meson-scripts/bpftool_build_skel)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/get_sys_incls found: YES (/home/shawn/workspace/scx-1.0.8/meson-scripts/get_sys_incls)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/test_sched found: YES (/home/shawn/workspace/scx-1.0.8/meson-scripts/test_sched)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/fetch_libbpf found: YES (/bin/bash /home/shawn/workspace/scx-1.0.8/meson-scripts/fetch_libbpf)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/build_libbpf found: YES (/home/shawn/workspace/scx-1.0.8/meson-scripts/build_libbpf)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/fetch_bpftool found: YES (/bin/bash /home/shawn/workspace/scx-1.0.8/meson-scripts/fetch_bpftool)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/build_bpftool found: YES (/bin/bash /home/shawn/workspace/scx-1.0.8/meson-scripts/build_bpftool)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/compile_scx_lib found: YES (/home/shawn/workspace/scx-1.0.8/meson-scripts/compile_scx_lib)
Program jq found: YES (/usr/bin/jq)
Program make found: YES (/usr/bin/make)
Program nproc found: YES (/usr/bin/nproc)
Message: Fetching libbpf repo
Library elf found: YES
Library z found: YES
Library zstd found: YES
Message: Fetching bpftool repo
Message: cpu=x86_64 bpf_base_cflags=['-g', '-O2', '-Wall', '-Wno-compare-distinct-pointer-types', '-D__TARGET_ARCH_x86', '-mcpu=v3', '-mlittle-endian', '-idirafter /usr/lib/llvm-18/lib/clang/18/include', '-idirafter /usr/local/include', '-idirafter /usr/include/x86_64-linux-gnu', '-idirafter /usr/include']
Program cargo found: YES (/usr/bin/cargo)
Program /home/shawn/workspace/scx-1.0.8/meson-scripts/cargo_fetch found: YES (/home/shawn/workspace/scx-1.0.8/meson-scripts/cargo_fetch)
Run-time dependency threads found: YES
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Dependency threads found: YES unknown (cached)
Found pkg-config: YES (/usr/bin/pkg-config) 1.8.1
Run-time dependency systemd found: YES 255
Found CMake: /usr/bin/cmake (3.28.3)
Run-time dependency openrc found: NO (tried pkgconfig and cmake)
Run-time dependency libalpm found: NO (tried pkgconfig and cmake)
Build targets in project: 59

sched_ext schedulers 1.0.8

  User defined options
    prefix: /home/shawn

Found ninja-1.11.1 at /usr/bin/ninja
shawn@shawn-mini-desktop:~/workspace/scx-1.0.8$ meson compile -C build
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/shawn/workspace/scx-1.0.8/build
ninja: Entering directory `/home/shawn/workspace/scx-1.0.8/build'
ninja: error: 'scheds/c/lib.bpf.o', needed by 'scheds/c/scx_simple.p/lib.bpf.skel.h', missing and no known rule to make it
shawn@shawn-mini-desktop:~/workspace/scx-1.0.8$ bpftool -V
bpftool v7.5.0
using libbpf v1.5
features: llvm, skeletons

```

**Comment by pingxiang-chen** [comment]
I change to use version 1.0.6 . It works.
