### ISSUE TITLE
scx_lavd: epp not changed with power mode under autopilot

### ISSUE THREAD

**Issue by rhjdvsgsgks** [sched-ext/scx#1127]
hi

i usually use powersave (power) for epp. which will limit max frequency to 800mhz. in this case, i start scx_lavd and rung some workload. in `scx_lavd --monitor`, it successfully discovered workload and switched power mode to performance. however, epp is still unchanged (powersave). which means max freq still capped at 800mhz.

is that a expected behavior? is that means i should switch epp to performance to provide a wider controllable frequency range for scx_lavd?

**Comment by multics69** [comment]
Yes, this is the expected behavior. The LAVD does not change the epp mode currently.
