### ISSUE TITLE
Ambiguity on "Scheduling cycle" subsection (OVERVIEW.md)

### ISSUE THREAD

**Issue by jacquetpi** [sched-ext/scx#117]
I'm trying to understand the Scheduling cycle from [Overview](https://github.com/sched-ext/scx/blob/main/OVERVIEW.md). I'm confused about step 3:

> When a CPU is ready to schedule, it first looks at its local DSQ.   If empty, it invokes .consume() which should make one or more scx_bpf_consume() calls to consume tasks from DSQ's. If a scx_bpf_consume() call succeeds, the CPU has the next task to run and .consume() can return. If .consume() is not defined, sched_ext will by-default consume from only the built-in SCX_DSQ_GLOBAL DSQ.

Operations referred from previous steps (```select_cpu()``` and  ```.dispatch()```) are from structure ```sched_ext_ops```  but ```.consume()``` is not. What is it then?

Error encountered:
```
 error: field designator 'consume' does not refer to any field in type 'struct sched_ext_ops'
```

**Comment by Decave** [comment]
Thanks for the report and sorry for the confusion, that is indeed a stale comment. I'm surprised we haven't updated it yet. I'll submit a fix for that today.

**Comment by Decave** [comment]
@jacquetpi closing this out. Please feel free to reopen or submit a separate issue if anything is still unclear.
