### ISSUE TITLE
scx_central causes system hang up on 6.7.1-scx1-2

### ISSUE THREAD

**Issue by shun159** [sched-ext/scx#135]
Upon starting `scx_central`, the system hangs up immediately. After the hang-up, neither keyboard input is responsive nor does the system switch to a crash kernel, making it difficult to gather information. Nonetheless, I have created this issue for now. Please let me know if any additional information is needed.

OS: Arch Linux (6.7.1-scx1-2)
CPU: i7-1165G7
scx: a4ff395d

**Comment by kkdwivedi** [comment]
Hello, I can look into this, but can you please more information on the steps to reproduce this? Does this happen in all cases (like even inside a VM) or only on a server or desktop machine? Do you run some specific application when it occurs? I haven't hit such an issue running it so far, but only more information will be helpful in getting to the bottom of this.

**Comment by shun159** [comment]
Hi, thank you for your response.

 I use the laptop machine to test `scx` samples, and I didn't verify if this issue occurs in a VM or under other cases. As mentioned earlier, upon starting `scx_central`, the system immediately hangs up. No any specific applications are running when this occurs.

If you have any suggestions on how to collect logs when the system hangs up, please let me know. I will attempt to repro the issue and I can provide logs when it occurs.

Thanks

**Comment by shun159** [comment]
After upgrading the kernel from `6.7.1-scx1-2` to `6.7.4.scx2-1`, it appears that system hang-ups are no longer occurring.
