### ISSUE TITLE
Unable to start scx_rusty after topology commit

### ISSUE THREAD

**Issue by kode54** [sched-ext/scx#147]
I am unable to start scx_rusty after https://github.com/sched-ext/scx/commit/8aba090d4f18d760f8a7a3adf1da4b5652f48de8 because it thinks I have 16 cores, 32 threads, when I actually have 8 cores, 16 threads:

```
> sudo scx_rusty
09:21:27 [INFO] CPUs: online/possible = 16/32
thread 'main' panicked at /usr/src/debug/scx-scheds-git/scx/rust/scx_utils/src/topology.rs:218:21:
Failed to open or read core_id file "/sys/devices/system/cpu/cpu16/topology/core_id"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ptr1337** [comment]
> I am unable to start scx_rusty after [8aba090](https://github.com/sched-ext/scx/commit/8aba090d4f18d760f8a7a3adf1da4b5652f48de8) because it thinks I have 16 cores, 32 threads, when I actually have 8 cores, 16 threads:
> 
> ```
> > sudo scx_rusty
> 09:21:27 [INFO] CPUs: online/possible = 16/32
> thread 'main' panicked at /usr/src/debug/scx-scheds-git/scx/rust/scx_utils/src/topology.rs:218:21:
> Failed to open or read core_id file "/sys/devices/system/cpu/cpu16/topology/core_id"
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```

Old issue, this is an issue in the linux kernel but the topology patch probably breaks the old fix for it.

See here:
https://github.com/sched-ext/sched_ext/issues/69#issuecomment-1796172180

Workaround is to boot with nr_cpus=16

**Comment by arighi** [comment]
Hm.. interesting, I'm wondering if this affects also functions like `scx_bpf_pick_idle_cpu()`, `scx_bpf_pick_any_cpu()`, and similar... like could they return a cpu id that doesn't really exist?

**Comment by ptr1337** [comment]
> I'll address this soon. We shouldn't have regressed rusty from the refactor. I needed to take care of something internally for Meta, but I should have the bandwidth to fix up Topology more completely soon.

I think it would be generally also important to have a fixup for the general issue instead of workaround that issue with sched-ext/scx-rusty.
The AMD Devs should really look into fixing that issue, since it could have also a bunch of other interactions with internal kernel configurations

**Comment by Byte-Lab** [comment]
This should be addressed with https://github.com/sched-ext/scx/pull/178. @kode54 could you please try out the latest rusty and let me know? Thanks.

**Comment by kode54** [comment]
I removed the `nr_cpus=16` from my kernel config to test, and now I get this crash trace:

```
thread 'main' panicked at src/main.rs:266:51:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x5785668ba1b6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9ddb4a97ccb07ddc
   1:     0x5785668e0290 - core::fmt::write::hd8d1384d900996df
   2:     0x5785668b7f6d - std::io::Write::write_fmt::h3d378959f4cebf0f
   3:     0x5785668b9f94 - std::sys_common::backtrace::print::h490bd4a39a58832d
   4:     0x5785668bb6b7 - std::panicking::default_hook::{{closure}}::h2bf493f402fae7cc
   5:     0x5785668bb419 - std::panicking::default_hook::h59354a0791fbc475
   6:     0x5785668bbb48 - std::panicking::rust_panic_with_hook::h04713cd2b736ff53
   7:     0x5785668bb9e9 - std::panicking::begin_panic_handler::{{closure}}::hdc1e5e7b41136df4
   8:     0x5785668ba6b6 - std::sys_common::backtrace::__rust_end_short_backtrace::h43faa053e6c80d44
   9:     0x5785668bb780 - rust_begin_unwind
  10:     0x5785662ea285 - core::panicking::panic_fmt::hc89f089f552084a6
  11:     0x5785662ea343 - core::panicking::panic::hf4a6066ae1a23b28
  12:     0x57856682f365 - core::option::Option<T>::unwrap::h6565705006f6118e
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/option.rs:931:21
  13:     0x57856632a93b - scx_rusty::Scheduler::init::h91632dcf82e30f41
                               at /usr/src/debug/scx-scheds-git/scx/scheds/rust/scx_rusty/src/main.rs:266:26
  14:     0x57856632fa1e - scx_rusty::main::h09a4785a28577050
                               at /usr/src/debug/scx-scheds-git/scx/scheds/rust/scx_rusty/src/main.rs:597:21
  15:     0x57856631807b - core::ops::function::FnOnce::call_once::he10fbcd2e93fb111
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/core/src/ops/function.rs:250:5
  16:     0x57856634087e - std::sys_common::backtrace::__rust_begin_short_backtrace::h94b4a70dea610822
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/sys_common/backtrace.rs:155:18
  17:     0x57856630f851 - std::rt::lang_start::{{closure}}::h29b4513bf332847c
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/rt.rs:166:18
  18:     0x5785668b1921 - std::rt::lang_start_internal::h4453343b6f899a15
  19:     0x57856630f82a - std::rt::lang_start::h80eeadea1ccc9208
                               at /usr/src/debug/rust/rustc-1.76.0-src/library/std/src/rt.rs:165:17
  20:     0x578566334ede - main
  21:     0x72e522895cd0 - <unknown>
  22:     0x72e522895d8a - __libc_start_main
  23:     0x5785662eab65 - _start
  24:                0x0 - <unknown>
```

**Comment by Byte-Lab** [comment]
That's weird. Could you please paste the output of `lscpu -e`?

**Comment by Byte-Lab** [comment]
Nevermind, ignore my request. I assume the BIOS is just reporting an incorrect number for `nr_possible`, so we're not finding a domain for the CPU when we iterate sysfs. @kode54 could you please try that patch?

**Comment by ptr1337** [comment]
> Nevermind, ignore my request. I assume the BIOS is just reporting an incorrect number for `nr_possible`, so we're not finding a domain for the CPU when we iterate sysfs. @kode54 could you please try #186?

Thats still the old bug from AMD side.
We discussed already in another issue about that...

**Comment by Byte-Lab** [comment]
> > Nevermind, ignore my request. I assume the BIOS is just reporting an incorrect number for `nr_possible`, so we're not finding a domain for the CPU when we iterate sysfs. @kode54 could you please try #186?
> 
> Thats still the old bug from AMD side. We discussed already in another issue about that...

Yes, my mistake. I came back to this issue after a while and should have reread it.

**Comment by Byte-Lab** [comment]
@kode54 do you still hit this issue even with the latest scx_rusty?

**Comment by kode54** [comment]
I'm not actively using Linux as my primary operating system right now, so I can't test. Recall that this issue was because of the absence of `nr_cpus=16` in my boot command line. I didn't feel like testing the workaround, because of the claimed inefficiency with handling the so-called "offline" CPUs.

**Comment by ptr1337** [comment]
> I'm not actively using Linux as my primary operating system right now, so I can't test. Recall that this issue was because of the absence of `nr_cpus=16` in my boot command line. I didn't feel like testing the workaround, because of the claimed inefficiency with handling the so-called "offline" CPUs.

That’s an issue, which only AMD currently can address. We’ve reported bugs to them, this issue is also still present on their newer zen4 platform. 

But sched-ext will handle this now correctly.

**Comment by Byte-Lab** [comment]
>I didn't feel like testing the workaround, because of the claimed inefficiency with handling the so-called "offline" CPUs.

No worries. This inefficiency has been addressed on the sched_ext side, but yes, the kernel itself will still have redundant allocations, iterations, etc for any incorrectly-listed-as-offline CPUs. Anyways, this should be addressed on the sched_ext side, so let's close for now and reopen if anyone else runs into it.
