### ISSUE TITLE
C sample schedulers failing with "`scx_bpf_switch_all` not found"

### ISSUE THREAD

**Issue by tzussman** [sched-ext/scx#184]
The following is happening when trying to run any of the C sample schedulers:

```console
$ sudo ./scx_simple
libbpf: extern (func ksym) 'scx_bpf_switch_all': not found in kernel or module BTFs
libbpf: failed to load object 'scx_simple'
libbpf: failed to load BPF skeleton 'scx_simple': -22
../scheds/c/scx_simple.c:81 [scx panic]: Invalid argument
Failed to load skel
```

This occurs when using scx sched-ext/scx@b7c06b9ed9f72cad83c31e39e9c4e2cfd8683a55 and sched-ext/sched_ext@13f2f03196d87e3a2dfecebcabcc0ad3da4d094e.

After some more testing it looks like the in-kernel examples under `tools/sched_ext` are working, so it doesn't seem to be a kernel config issue.

**Comment by htejun** [comment]
Yeah, right now, there's API mismatch between the kernel and scx repo. We're waiting on libbpf-rs updates to add compat features. For the time being, please use either the sched-ext/sched_ext-ci branch or a pre-packaged kernel.

**Comment by kode54** [comment]
linux-cachyos 6.8.0-1 also has that function in the sched-ext patch set it is applying, so I guess that's why I didn't experience missing functions with the current schedulers.

**Comment by htejun** [comment]
This should be resolved now. Closing. Please reopen if it's not resolved.
