### ISSUE TITLE
Compilation fail to "generate libbpf with custom command"

### ISSUE THREAD

**Issue by matteo-dinoia** [sched-ext/scx#205]
While trying to compile the entire project, following the steps outilined on the README.md, it gives error while generating libbpf with custom command. The error log (in file below) talk about various unexpected arguments.

Extra information which could be useful: 
- last week I did build it successfully, but now i don't seem to be able to build even older version (i don't remember the exact version I built)
- the only change in the system was the installation of rustup instead of rust (but even reinstalling rust doesn't fix it) and package upgrade on Arch Linux.
- trying to build with dynamic linking also fail at step "[11/39] Generating bpftool_target with a custom command" with very similar errors.

Sorry in advance if it is a stupid problem on my parts, but I cannot seem to be able to fix it.

[log.txt](https://github.com/sched-ext/scx/files/14814715/log.txt)

**Comment by ptr1337** [comment]
Could you please try the AUR packages?

**Comment by matteo-dinoia** [comment]
Tried and result are:
- bin package: work
- aur git pacakage: same problem as from source
- cachyos git package: is not a git(? probably is build by them) doesn't compile and just install fine as the bin package

**Comment by ptr1337** [comment]
Oh, I see the issue probably. Could you disable sccache?
Not sure, where you have enabled it.

**Comment by matteo-dinoia** [comment]
I didn't enabled it it is just installed on my machine. Removing it fixed the issue.

**Comment by ptr1337** [comment]
> I didn't enabled it it is just installed on my machine. Removing it fixed the issue.

I think you can close this issue then, since it seems like there is a issue with sccache and not scx-scheds.

**Comment by htejun** [comment]
scx has a really hacky workaround in build script which may be why it's failing with sccache. I'll try sccache and see if I can fix it.

**Comment by htejun** [comment]
So, I tested with sccache and it fails when building `meson-scripts/cc_cflags_probe.c`. We aren't doing anything special at that point and it seems like an issue with sccache and meson automatically uses sccache if installed. I'll update README with an instruction on how to disable using sccache while building.
