### ISSUE TITLE
scx_rusty errors/exits on suspend/resume

### ISSUE THREAD

**Issue by arighi** [sched-ext/scx#242]
When a system is suspended the CPUs are going offline, this triggers a call to the `.cpu_offline` callback (and `.cpu_online` on resume), that is considered an error / exit condition by `scx_rusty`. That means `scx_rusty` currently does not support PM events, even if they shouldn't be considered error / exit conditions.

Maybe exiting in `rusty_cpu_online/offline`  should be optional (via a command line)? Or somehow detect that the "offline/online" event was caused during suspend/resume. Other ideas?

**Comment by arighi** [comment]
Example (when my laptop goes in suspend):

```
DEBUG DUMP
================================================================================

cpuhp/1[21] triggered exit kind 1025:
  scx_bpf_error (CPU 1 went offline)

Backtrace:
  scx_bpf_error_bstr+0x141/0x1a0
  bpf_prog_c08171a7d2910176_rusty_cpu_offline+0x5f/0x63

```

**Comment by Byte-Lab** [comment]
Ah, @arighi I think this is due to you running on a kernel that doesn't yet support `scx_bpf_exit()`. In that scenario, the scheduler will exit with `RUSTY_EXIT_HOTPLUG`, which should be detected by rusty and instead cause the scheduler to restart.

**Comment by arighi** [comment]
@Byte-Lab yep, I still need to rebase the Ubuntu kernel on a more recent sched-ext kernel, ok if it's something that will be handled properly with the new kernel it's probably a non-issue then, thanks!
