### ISSUE TITLE
Is CONFIG_PAHOLE_HAS_BTF_TAG needed?

### ISSUE THREAD

**Issue by vanfanel** [sched-ext/scx#251]
Hi there,

I'm trying to setup a self-built 6.8.8 kernel with the Cachyos patchset to experiment with sched-ext.

I have seen on Phoronix that these kernel config options are supposedly needed for sched-ext to work:

```
# essential configs to enable sched_ext
CONFIG_BPF=y
CONFIG_SCHED_CLASS_EXT=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_BPF_JIT_DEFAULT_ON=y
CONFIG_PAHOLE_HAS_BTF_TAG=y
CONFIG_DEBUG_INFO_BTF=y
```

Is that correct? I mean, is `CONFIG_PAHOLE_HAS_BTF_TAG` really needed?
It seems to depend on `CONFIG_CC_IS_CLANG` which is an additional hurdle since I have never built the kernel with CLANG (which is needed for sched-ext anyway, but still I would like to be sure of what am I doing and why).

Thanks!

**Comment by arighi** [comment]
I've always built the sched-ext Ubuntu kernel using gcc and all the schedulers have been functioning properly without `CONFIG_PAHOLE_HAS_BTF_TAG`. Therefore,, I am pretty confident in saying that this option is not strictly needed in general (but it's probably required if you build the kernel using clang).

**Comment by vanfanel** [comment]
@arighi Thanks alot for chiming in! 
What about `CONFIG_DEBUG_INFO_BTF`, is that one needed for working sched_ext?
And I have `CONFIG_DEBUG_INFO_DWARF5`, but @bunkbail says that `CONFIG_DEBUG_INFO_DWARF4` is needed, what do you think?

**Comment by arighi** [comment]
@vanfanel `CONFIG_DEBUG_INFO_BTF` is mandatory in order to have access to `/sys/kernel/btf/vmlinux`.

About `CONFIG_DEBUG_INFO_DWARF4` I don't think it's required, I actually have `CONFIG_DEBUG_INFO_DWARF5` in my kernel...

**Comment by arighi** [comment]
BTW, as a reference to the required kernel configs, you can always check https://github.com/sched-ext/sched_ext/blob/sched_ext/.github/workflows/sched-ext.config

**Comment by vanfanel** [comment]
@arighi Thanks, I have built a 6.8.8 kernel with `CONFIG_DEBUG_INFO_BTF` enabled too.
Do you happen to know what option provides `exit_dump_len`? I have this error when running the schedulers, which seems to point to a missing kernel feature:
```

root@debian:~# scx_rustland 
16:06:37 [INFO] libbpf: struct_ops rustland: member exit_dump_len not found in kernel, skipping it as it's set to zero

Error: Failed to attach struct ops

Caused by:
    bpf call "libbpf_rs::map::Map::attach_struct_ops::{{closure}}" returned NULL
```

**Comment by vanfanel** [comment]
Ok, I got this working (no idea why it was failing, I would really like to document it here, but I rebuilt the kernel with new options and it's working now, no idea what I changed, really!)
