### ISSUE TITLE
scx_lavd fails to load

### ISSUE THREAD

**Issue by Galcian79** [sched-ext/scx#269]
Since kernel update `6.8.9` and `scx-scheds 0.1.9.r40.g07b521b-1` scx_lavd fails to load with error `Operation not supported (os error 95)`.

[scx_lavd.log](https://github.com/sched-ext/scx/files/15223429/scx_lavd.log)

**Comment by sirlucjan** [comment]
You've to install 0.1.9 version for 6.8. -git version works only with 6.9

**Comment by Galcian79** [comment]
> You've to install 0.1.9 version for 6.8. -git version works only with 6.9

Thanks for clarification.
