### ISSUE TITLE
scx_lavd: Failed to load BPF program

### ISSUE THREAD

**Issue by vax-r** [sched-ext/scx#315]
## Description
After sync with the latest repo, I tried to recompile and load the `scx_lavd` scheduler into the kernel, and the error message bump up.
```
Error: Failed to load BPF program

Caused by:
    Operation not supported (os error 95)
```
Also looked at `dmesg` for more information, but empty message generated in kernel space.

## Expected behavior
`scx_lavd` should be able to load into the kernel and work as expected.

**Comment by ptr1337** [comment]
Works fine here.

Which Kernel are you running? The 6.8 patchset is not compatible with the latest git of scx_lavd due cpufreq support missing.

**Comment by vax-r** [comment]
> Works fine here.
> 
> Which Kernel are you running? The 6.8 patchset is not compatible with the latest git of scx_lavd due cpufreq support missing.

I am running on `6.8.0-32-generic`
```
$ uname -r
6.8.0-32-generic
```

Umm so I have to update my kernel version, may I ask where to get it ?

**Comment by ptr1337** [comment]
> > Works fine here.
> > Which Kernel are you running? The 6.8 patchset is not compatible with the latest git of scx_lavd due cpufreq support missing.
> 
> I am running on `6.8.0-32-generic`
> 
> ```
> $ uname -r
> 6.8.0-32-generic
> ```
> 
> Umm so I have to update my kernel version, may I ask where to get it ? I followed the instructions by [Install instructions by Distros](https://github.com/sched-ext/scx/blob/main/INSTALL.md#ubuntu) to installed my kernel .

@arighi 
Would you maybe update the kernel either to the latest patchset for 6.8 or push the 6.9 one?
LAVD currently requires cpufreq support, which seems like is not maintained in your repository.

**Comment by arighi** [comment]
I'm planning to update the sched_ext Ubuntu kernel when I get back from OSPM, probably to the latest 6.8 patch set, to stay aligned with the generic kernel

**Comment by vax-r** [comment]
> I'm planning to update the sched_ext Ubuntu kernel when I get back from OSPM, probably to the latest 6.8 patch set, to stay aligned with the generic kernel

@arighi 
Thanks alot !
Then I'll close the issue then, I think after using your latest kernel the problem can be solved. Thank you.
