### ISSUE TITLE
Musl support

### ISSUE THREAD

**Issue by Kawanaao** [sched-ext/scx#319]
Hello! Today I encountered scx compilation and received an error

```rust
error[E0063]: missing fields `sched_ss_init_budget`, `sched_ss_low_priority`, `sched_ss_max_repl` and 1 other field in initializer of `sched_param`
    --> src/bpf.rs:377:34
     |
377 |          let param: sched_param = sched_param { sched_priority: 0 };
     |                                   ^^^^^^^^^^^ missing `sched_ss_init_budget`, `sched_ss_low_priority`, `sched_ss_max_repl` and 1 other field
```

Understanding the problem, I discovered that the libc library, in the presence of musl, [has additional fields in sched_param](https://github.com/rust-lang/libc/blob/acc7bb1a38e2b9d6a18f28279d80d464c4c25089/src/unix/linux_like/mod.rs#L105-L115)

**Comment by arighi** [comment]
@Kawanaao thanks for reporting this, can you check if #320 fixes this build failure?
