### ISSUE TITLE
sched_ext: Elden Ring heavy stuttering

### ISSUE THREAD

**Issue by hivehivemind** [sched-ext/scx#376]
Elden Ring is presenting intense stuttering in any game area, resolution or frame rate. Tested with lavd (bad), nest (bad), rusty (worse), and rustland (unplayable). Stopping scx.service, falling back to BORE in CachyOS, solves the problem. Dark Souls 3, from the same engine, is normally working with sched_ext.

Ryzen 7 5800X3D
RX 7900 XT
16GB (2x8) 3800 MHz CL14 RAM - running fine grained OC
ROG Strix X570-i - PSS, NX, Global C States disabled (happens with PSS enabled too)

Happens on Nobara 39 with [linux-cachyos kernel](https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos), CachyOS itself (linux-cachyos 6.9, linux-cachyos-deckify 6.9, linux-cachyos-rc 6.10, linux-cachyos-lto).

`# scx_lavd -s $(nproc) 2> elden_ring.log` attached.
[elden_ring.log](https://github.com/user-attachments/files/15907369/elden_ring.log)

**Comment by multics69** [comment]
If possible, could you please share rough FPS numbers? It seems to work fine on my SteamDeck.

**Comment by arighi** [comment]
AMD... hm... I'm wondering if we're still facing a similar `nr_cpus` issue again (see https://github.com/sched-ext/scx/issues/147)... Can you try to boot your kernel with `nr_cpus=16`?

**Comment by hivehivemind** [comment]
Uploaded RADV vs BORE in Elden Ring here: https://flightlessmango.com/games/38004/logs/5460
Context:
- 1600x900 (exclusive fullscreen), game auto-preset High, no mods, online
- Vulcano Manor rooms corridor. Just walking forward and backwards not touching the camera.
- CachyOS' KDE Plasma desktop

My normal play happens in gamescope embedded, 4K, mix of high-max settings, er-patcher for 90 FPS (game hard locks 60 by default), offline. Stutters are more drastic in the 90 FPS context.

Added `nr_cpus=16` to /etc/sdboot-manage.conf `LINUX_OPTIONS` env var -> `# sdboot-manage gen`. No change.

![frame-time](https://github.com/sched-ext/scx/assets/18638858/42192969-179a-4118-a9bc-33b15d23bc08)
![minmaxaverage](https://github.com/sched-ext/scx/assets/18638858/7af77936-af31-450f-ad73-9322242b1f4b)

**Comment by multics69** [comment]
What? The results are very different from one on StreamDeck. I will install the same CacheOS KDE to reproduce the problem. Thanks a lot @hivehivemind !

**Comment by multics69** [comment]
@hivehivemind -- Does it also happen in other stages besides Vulcano Manor?

**Comment by hivehivemind** [comment]
> @hivehivemind -- Does it also happen in other stages besides Vulcano Manor?

Replying here for visibility too. Yes, it happens on any game stage, although it's more severe in ones with more asset density such as Vulcano Manor and Leyndell. These two we see the stutter while standing still.

**Comment by multics69** [comment]
I tested it on 2 different AMD laptops. Now I understand what you mean while the sutters that I observed is much less severe. I hope they should follow the same pattern with you. I will work on it.

**Comment by multics69** [comment]
Please try PR #383 . It works okay in my setting while I didn't test the exact same stages.

**Comment by multics69** [comment]
@hivehivemind  -- PR #386 should further reduce micro-stutters (while I was not able to play on the same stages). Please try it out.

**Comment by neon-grim** [comment]
This issue appears to be back, at least on my end. when playing several from software titles (elden ring, nightreign and dark souls 3) severe stutter can be observed when the following schedulers are used: bpfland, lavd and rusty. Killing the process and reverting back to CFS solves the issue. BORE scheduler also doesnt seem to suffer from this.

I'm currently using version  1.0.13 available through nixos unstable.

**Comment by arighi** [comment]
This is just a guess: scx schedulers are less conservative than EEVDF/BORE in terms of migrations, so this might be an issue with these games and your particular CPU topology.

Can you try scx_flash from the flash-next branch? (it's a bit more conservative with migrations, especially with interactive tasks)

Also scx_p2dq should be able to mitigate this issue as well. But again, this is just a guess.

**Comment by neon-grim** [comment]
> reply to https://github.com/sched-ext/scx/issues/376#issuecomment-2992233292

I'll give it a try. I'm currently running a 7800X3D, I cant say how its topology could have an adverse effect to the game when using LAVD or BPFLAND. I'll report back with my findings.

This is currently my setup:

- CPU: 7800X3d
- GPU: 7900XTX
- RAM: 2x16GB 6000 MHz CL 30
- Kernel: 6.15.1 latest mainline nixos kernel
- Mesa: 25.1.2
- Compositor: Hyprland 0.49.0

**Comment by neon-grim** [comment]
> reply to https://github.com/sched-ext/scx/issues/376#issuecomment-2992233292

I tested with scx_flash and the stuttering has been severally reduced. CFS/BORE still runs the game better. I sadly wasnt able to test the second one, since I cant set it in my nixos config.

**Comment by arighi** [comment]
> > reply to [#376 (comment)](https://github.com/sched-ext/scx/issues/376#issuecomment-2992233292)
> 
> I tested with scx_flash and the stuttering has been severally reduced. CFS/BORE still runs the game better. I sadly wasnt able to test the second one, since I cant set it in my nixos config.

Just to make sure, this is with scx_flash from this branch https://github.com/sched-ext/scx/tree/flash-next right? (not stock scx_flash).

Also, can you share the output of `lscpu -e`? Thanks.

Edit: and if you haven't done already, can you try running `scx_flash -w` and see if it makes any difference?

**Comment by neon-grim** [comment]
> reply to https://github.com/sched-ext/scx/issues/376#issuecomment-2993967770

Sorry for my very late reply, had a lot of stuff to do IRL. No, I dont have access to the flash branch on nixos and sadly I dont know how I would go about getting this working.
