### ISSUE TITLE
README : Incorrect description about behavior of scx_XXX scheduler

### ISSUE THREAD

**Issue by yushoyamaguchi** [sched-ext/scx#426]
Currently, there is a statement in the README that if you install scx_XXX, it means that all tasks will be moved there.
https://github.com/sched-ext/scx/blob/274bcf7f02ea8d90c7c6308af6a891a31ba45e14/README.md?plain=1#L67

However, in [this commit](https://github.com/sched-ext/scx/commit/7c9aedaefe6f1da94c59d143cc2225a87823addd), I thought the change was made so that simply installing scx_XXX would not move the task to this scheduler?

If so, I felt the README description should be changed.
I apologize if I have missed something.

ref : https://lore.kernel.org/r/all/a0e9dea5a434a471576f192b980ad48cb40b742a.camel@linux.ibm.com/T/

**Comment by minosfuture** [comment]
@yushoyamaguchi thanks for the question. Let me help clarify a few things.

1. "When the BPF scheduler is loaded and SCX_OPS_SWITCH_PARTIAL is not set in ops->flags, all SCHED_NORMAL, SCHED_BATCH, SCHED_IDLE, and SCHED_EXT tasks are scheduled by sched_ext." This is described in the linux ext doc.
2. In `scx_simple`, this flag is not set. So it is true that all tasks in the aforementioned classes will be switched to ext, when `scx_simple` is loaded.
3. [the commit you sent](https://github.com/sched-ext/scx/commit/7c9aedaefe6f1da94c59d143cc2225a87823addd) is not disabling switching all. It's the kernel code that checks the flag and decides whether to switch a task or not. If interested, you may find `task_should_scx` function in `linux/kernel/sched/ext.c` and read more.

I hope this helps.

**Comment by yushoyamaguchi** [comment]
I've understood.
Thank you.
