### ISSUE TITLE
scx_lavd: Error: Failed to load BPF program (invalid argument (os error 22))

### ISSUE THREAD

**Issue by ltsdw** [sched-ext/scx#440]
Hello there, recently rustland stopped working.
Back when I was not using the git version of the package, two versions back it was working normally, here I'm using the git version as to be sure it wasn't fixed already.

```
uname -r
6.9.10-1
```

```
pacman -Qi scx-scheds-git 
Version         : 1.0.1.r10.gcb86768-1
```

```
bpftool --version
bpftool v7.4.0
using libbpf v1.4
features: llvm, skeletons
```

[scx_lavd -vvv output.txt](https://github.com/user-attachments/files/16288748/log.txt):
```
...
cannot pass in iter at an offset=-64
expected uninitialized iter_scx_dsq as arg #1
processed 77 insns (limit 1000000) max_states_per_insn 0 total_states 5 peak_states 5 mark_read 4
-- END PROG LOAD LOG --
libbpf: prog 'lavd_select_cpu': failed to load: -22
libbpf: failed to load object 'bpf_bpf'
libbpf: failed to load BPF skeleton 'bpf_bpf': -22
Error: Failed to load BPF program
```

Also I don't know if it's relevant but started two versions back a warning (it's just a warning, the scheds works normally, besides lavd):

```
20:25:11 [WARN] libbpf: map 'rustland': BPF skeleton version is old, skipping map auto-attachment...
```

**Comment by ptr1337** [comment]
You need to update to the 6.10 Kernel/Patchset. There were for the "for-6.11" Patch to upstream sched-ext into the kernel a bunch of features deprecated. This will be added in the future again, as soon the initial MR is merged.

**Comment by ltsdw** [comment]
Perfect then, will compile a 6.10 version once it gets to stable. Thanks, closing.
