### ISSUE TITLE
[scx-kernel-releases] v6.10.1 patch file is empty

### ISSUE THREAD

**Issue by torvic9** [sched-ext/scx#448]
I couldn't open an issue in the "scx-kernel-releases" repository, so I'll just leave a short message here, to say that the latest [v6.10.1 release](https://github.com/sched-ext/scx-kernel-releases/releases/tag/v6.10.1-scx1) has an empty patch file.

**Comment by sirlucjan** [comment]
You can use this one: https://github.com/CachyOS/kernel-patches/blob/master/6.10/sched/0001-sched-ext.patch

**Comment by ptr1337** [comment]
Issue should be solved in the recent release, please close the issue :)
