### ISSUE TITLE
sched_ext: BPF scheduler "lavd" errored, disabling

### ISSUE THREAD

**Issue by anh0516** [sched-ext/scx#476]
Built from the current main branch, with Linux 6.10.3. It failed while playing Honkai: Star Rail.
```
[ 2768.754205] sched_ext: BPF scheduler "lavd" errored, disabling
[ 2768.754207] sched_ext: runnable task stall (kworker/11:1[86] failed to run for 37.632s)
[ 2768.754208]    process_scheduled_works+0x1ba/0x3d0
[ 2768.754212]    worker_thread+0x37f/0x670
[ 2768.754213]    kthread+0x281/0x2a0
[ 2768.754213]    ret_from_fork+0x2e/0x40
[ 2768.754215]    ret_from_fork_asm+0x1a/0x30
```
The thread in question with ID 86 is ```kworker/11:1-mm_percpu_wq```, which says absolutely nothing about what exactly went wrong.

I stopped and started the scheduler and it's happy now. I do not have a reliable way to reproduce this and it hasn't happened again, but I figured I would report it anyway as it indicates lavd is not 100% stable in its current condition.

**Comment by multics69** [comment]
Thank you, @anh0516, for reporting the problem. Could you share your rough scenario of how to trigger the watchdog error? I will try to reproduce the problem from my side.

**Comment by anh0516** [comment]
It just failed randomly while playing 2.4's story content twice. Not reproducible at all, but if I play some more, it could hopefully happen again. What I put in this issue was all the info I have.

Do you have any recommendations on debugging or profiling tools that I could set up so I can try to better capture the issue?

**Comment by multics69** [comment]
@anh0516 Do you use either multi-CCX or multi-NUMA processor?

**Comment by anh0516** [comment]
I'm running an R5 5600G, so single-CCX.

**Comment by htejun** [comment]
Please reopen if still reproducible.

**Comment by anh0516** [comment]
I haven't had any issues since, so I think it's fine now.
