### ISSUE TITLE
Huge log files

### ISSUE THREAD

**Issue by Kawanaao** [sched-ext/scx#521]
Hi all!

I would like to suggest introducing the LOG_LEVEL variable or simply LOG=false into the services (for openrc, I don’t know if this is relevant for systemd), the reason is that scx produces too much information as a service, 140MiB of logs are collected in one day
logrotate, unfortunately, will be redundant due to the need to see errors as well

**Comment by sirlucjan** [comment]
In systemd, we limited the size of the logo to 50M [1]. 
Maybe @nycko123  will know what to do with openrc. 

1. https://github.com/sched-ext/scx/blob/main/services/systemd/journald%40sched-ext.conf#L3

**Comment by Kawanaao** [comment]
> In systemd, we limited the size of the logo to 50M [1]. Maybe @nycko123 will know what to do with openrc.
> 
> 1. https://github.com/sched-ext/scx/blob/main/services/systemd/journald%40sched-ext.conf#L3

In openrc this is done via logrotate, but in any case the problem is more likely that there are too many entries in the logs, I would like to have fewer of them or disable them, since they overwrite all the most important things

**Comment by sirlucjan** [comment]
rusty, lavd and bpfland have scx_stats support (in -git version). Could you check?

**Comment by ptr1337** [comment]
There are no log files anymore, this gets handled via scx_stats and of the schedulers --monitor function. I think we can close that issue.
