### ISSUE TITLE
Create Cargo workspace for Rust schedulers

### ISSUE THREAD

**Issue by vimproved** [sched-ext/scx#546]
It would be helpful for packaging purposes if there was a top-level Cargo workspace that contained all of the Rust schedulers as members, since it would allow compiling with only one invocation of Cargo instead of many individual ones. Additionally, it would enable all schedulers to share a Cargo.lock, which would have multiple benefits.

**Comment by htejun** [comment]
Thanks for the suggestion. This has been an annoying problem for quite a while and it's so much better with cargo workspace.
