### ISSUE TITLE
Update scx_layered docs to match layer stats

### ISSUE THREAD

**Issue by hodgesds** [sched-ext/scx#701]
Update the documentation for [layer stats](https://github.com/sched-ext/scx/blob/main/scheds/rust/scx_layered/src/main.rs#L366)  to be in sync with the [`LayerStats`](https://github.com/sched-ext/scx/blob/main/scheds/rust/scx_layered/src/stats.rs#L49) struct, or even better yet automate the documentation.

**Comment by minosfuture** [comment]
how about using `StatsFieldAttrs::desc` to generate `#[doc = ...]` in `Stats` macro?
and add a doc link like ```Global statistics: see [`SysStats`]```

**Comment by hodgesds** [comment]
> how about using `StatsFieldAttrs::desc` to generate `#[doc = ...]` in `Stats` macro? and add a doc link like `` Global statistics: see [`SysStats`] ``

Awesome idea, can you send a pull request?

**Comment by minosfuture** [comment]
Please review #703, thanks!

**Comment by hodgesds** [comment]
Thanks @minosfuture for working on this!
