### ISSUE TITLE
scx_layered: Add per layer time slices to stats

### ISSUE THREAD

**Issue by hodgesds** [sched-ext/scx#720]
In `scx_layered` the time slice can be [configured per layer](https://github.com/sched-ext/scx/blob/main/scheds/rust/scx_layered/src/main.rs#L493). This should be added to the [`LayerStats`](https://github.com/sched-ext/scx/blob/main/scheds/rust/scx_layered/src/stats.rs#L51)  for each layer. During stats [refresh](https://github.com/sched-ext/scx/blob/main/scheds/rust/scx_layered/src/main.rs#L852) read the time slice duration (from the bpf skel) to the layer and add it to the stats. Finally, update the [format](https://github.com/sched-ext/scx/blob/main/scheds/rust/scx_layered/src/stats.rs#L218) method for `LayerStats` to print the per layer time slices.

**Comment by minosfuture** [comment]
hi @hodgesds, I submitted #732, please review. Thanks!

**Comment by hodgesds** [comment]
Thank you for implementing this!
