### ISSUE TITLE
scx_lavd: libbpf: prog 'fexit_down': failed to attach: Device or resource busy

### ISSUE THREAD

**Issue by anh0516** [sched-ext/scx#794]
The new futex locking in scx_lavd is not working for me.

```
libbpf: prog 'fexit_down': failed to attach: Device or resource busy
libbpf: prog 'fexit_down': failed to auto-attach: -16
Error: Failed to attach non-struct_ops BPF programs
```
```
[pid  2754] bpf(BPF_LINK_CREATE, {link_create={prog_fd=18, target_fd=0, attach_type=BPF_TRACE_FEXIT, flags=0}}, 64) = -1 EBUSY (Device or resource busy)
```
[strace.log](https://github.com/user-attachments/files/17356146/strace.log)
[lavd.log](https://github.com/user-attachments/files/17356147/lavd.log)
[config.txt](https://github.com/user-attachments/files/17356156/config.txt)

Am I missing a kernel configuration option? I'd expect `EOPNOTSUPP` in that case. I took a look at the scheduler code and the relevant kernel code. It's not really obvious what's going on under the hood, and `BPF_TRACE_FEXIT` isn't an optional feature. 

Is this a reproducible issue? What tools can I use to debug this?

**Comment by multics69** [comment]
Thank you @anh0516 for reporting the problem. Is this problem reproducible and happens all the time? Or does it happen from time to time?

**Comment by anh0516** [comment]
When starting the scheduler, every time.

After some more debugging, I found that enabling `CONFIG_FUNCTION_TRACER` solves the problem. tracefs shows that the function tracer isn't actually being used, so it must be one of the nonconfigurable dependencies of it that is necessary for scx_lavd to function.

I didn't mention it because it was irrelevant to my issue, but there were also complaints about `CONFIG_CGROUP_BPF` being disabled. These don't cause the scheduler to fail, and you cannot even see them without using `strace`. (You can see the successful behavior when `CONFIG_CGROUP_BPF` is disabled in the `strace` I uploaded.) I don't know what the ramifications are of not having it enabled but I figured I'd point it out.
