### ISSUE TITLE
sched_ext: "<scheduler>" does not implement cgroup cpu.weight 

### ISSUE THREAD

**Issue by anh0516** [sched-ext/scx#800]
When starting any scheduler, in `dmesg` I see:

```
sched_ext: "bpfland" does not implement cgroup cpu.weight
```

```
sched_ext: "lavd" does not implement cgroup cpu.weight
```

```
sched_ext: "rusty" does not implement cgroup cpu.weight
```

etc.

Is this normal and expected or am I missing a kernel feature? I do have `cpu.weight` under cgroup slices.

**Comment by hodgesds** [comment]
I believe this file will be available if [`SCX_OPS_HAS_CGROUP_WEIGHT`](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/sched/ext.c#n123) is set on the flags ([example](https://github.com/sched-ext/scx/blob/main/scheds/c/scx_flatcg.bpf.c#L947)). IIRC the value in the file doesn't have any meaning when running with a sched_ext scheduler (@htejun probably knows best).

**Comment by htejun** [comment]
Yeah, those are expected. The kernel is just saying that cgroup has cgroup CPU weights set but the loaded scheduler doesn't support it and thus the config is ignored.

**Comment by anh0516** [comment]
Ah, got it. Thanks.
