### ISSUE TITLE
scx_layered: prevent dsq starvation w/ a timer

### ISSUE THREAD

**Issue by likewhatevs** [sched-ext/scx#828]
scx_layered: prevent lo_fallback_dsq starvation w/ affinitized

To prevent stalls from affinitized threads being placed in layers which may not contain the specified CPU, place affinitized threads in lo_fallback_dsq.

To prevent lo_fallback_dsq from being starved, use a bpf timer to periodically set an atomic flag to true. 

When this flag is true, from dispatch, use a dsq iterator to check if the first task in lo_fallback_dsq has a wait time greater than some time interval (5 or 15s). If such a task exists, set that atomic flag to false and consume lo_fallback_dsq; otherwise end this iteration and continue as usual.

**Comment by likewhatevs** [comment]
@htejun did I capture this right (I think so and it kinda makes sense)?

**Comment by hodgesds** [comment]
Added some timer helpers in #832 that should help with this.

**Comment by htejun** [comment]
Yes, for the most part. I'm not sure we want to put all affinitized tasks into lo fallback and lo fallback needs macro fairness implemented too. For the problem at hand, I think the immediate solution is implementing low frequency periodic scanning of all DSQs to prevent starvation of unlucky affinitized tasks.

**Comment by likewhatevs** [comment]
In theory https://github.com/sched-ext/scx/pull/855 ought to prevent starvation w/ the right config so gonna try that first.
