### ISSUE TITLE
scx_lavd: comp_preemption_info access not initialized variable

### ISSUE THREAD

**Issue by archerbroler** [sched-ext/scx#845]
In try_yield_current_cpu, prm_run and prm_wait's cpuc is not initialized before can_task1_kick_task2.
In can_task1_kick_task2, the comp_preemption_info is called, which access prm_b->cpuc directly like this:
```
static int comp_preemption_info(struct preemption_info *prm_a,
				struct preemption_info *prm_b)
{
	/*
	 * Never preeempt a lock holder.
	 */
	if (prm_b->cpuc->lock_holder)
		return 1;
```

But I am not crashed with this, I don't know why. But it seems not correct.

**Comment by multics69** [comment]
Thank you @archerbroler for catching this out! I fixed it in PR https://github.com/sched-ext/scx/pull/846
