### ISSUE TITLE
scx_lavd: enqueue preempt current CPU may not work

### ISSUE THREAD

**Issue by archerbroler** [sched-ext/scx#849]
In lavd_enqueue, try_find_and_kick_victim_cpu and try_yield_current_cpu may preempt current waker CPU.
When they did, they set the slice of curr to 0, but with no kick.
In the tick path, SCX Core will ensure resched_curr are called when slice is 0, but not the enqueue path.
This cause the enqueue preempt current path actually not preempted until tick.  
I don't think this is by design.

**Comment by multics69** [comment]
Thank you, @archerbroler, for catching this. I will investigate the code once again and let you know.

**Comment by archerbroler** [comment]
glad to discuss LAVD with you. LAVD is promising, I really like it.
