### ISSUE TITLE
scx_lavd: Core compaction in try_find_and_kick_victim_cpu is actually not considered

### ISSUE THREAD

**Issue by archerbroler** [sched-ext/scx#857]
In try_find_and_kick_victim_cpu, the available victim cpumask is created like this:

```
	cpumask = cpuc_cur->tmp_t_mask;
	cpdomc = MEMBER_VPTR(cpdom_ctxs, [dsq_id]);
	cd_cpumask = MEMBER_VPTR(cpdom_cpumask, [dsq_id]);
	if (!cpdomc || !cd_cpumask || !cpumask)
		return false;

	bpf_cpumask_and(cpumask, cast_mask(cd_cpumask), p->cpus_ptr);
```

The cpuc_cur->tmp_t_mask initial setted to cpumask is actually not used, which will be overwrite in bpf_cpumask_and.

The cpumask(point to cpuc_cur->tmp_t_mask) will be set to (Domain CPU &p->cpus_ptr), which not have the active_cpumask and   ovrflw_cpumask information.

**Comment by multics69** [comment]
`cpuc_cur->tmp_t_mask` (`cpumask`) is a temporary space to avoid expensive cpumask alloc/free ops.  Once the target  `cpumask`  is calculated (`bpf_cpumask_and`), `cpumask` is used for `find_victim_cpu()`. Hmm... am I missing something? Or does it make sense?

**Comment by archerbroler** [comment]
The victim cpumask is calc like this:
bpf_cpumask_and(cpumask, cast_mask(cd_cpumask), p->cpus_ptr);
That means all the CPU in the selected CPU's Domain which may include Core compaction' overflow CPU.
I think the overflow CPU is not a valid victim CPU.

cpuc_cur->tmp_t_mask may be updated in select_cpu,  which will include only the active CPU. So, keep using the previous value may make some sense. But it is not always update in select_cpu path, so use that value directly is not correct too.

So, I just think your intended code is like this:
bpf_cpumask_and(cpumask, cpumask, p->cpus_ptr);
bpf_cpumask_and(cpumask, cpumask, cast_mask(cd_cpumask));

**Comment by multics69** [comment]
It is my intention to preempt overflow CPUs too. Otherwise, we unintendedly penalize tasks on active CPUs.
