### ISSUE TITLE
scx_utils: Provide scheduler flags in a compatible way

### ISSUE THREAD

**Issue by htejun** [sched-ext/scx#863]
Some of SCX flags are derived from scheduler core flags and are subject to change. It's less likely but other flags may change too. When the flag values are used directly, they're substituted to the value that was defined at the time of compilation and the binary wouldn't be able to function correctly when loaded on a kernel which uses different values for these flags.

All the SCX flags are enums and can be obtained using CO-RE helpers. Provide compat helpers that put the flag values in `const volatile` variables which are set at load time so that scheduler binaries can work across kernels with different flag values.

**Comment by etsal** [comment]
Completed with #894
