### ISSUE TITLE
scx_lavd: dispatch task to cpu not allowed

### ISSUE THREAD

**Issue by archerbroler** [sched-ext/scx#864]
In lavd_dispatch, if use_full_cpus() is true, will call consume_task to consume the dsq.
Which will skip the task's cpus_ptr test.
This resulted CPU actually run task which not allowed to run on that CPU.

**Comment by multics69** [comment]
Thank you for finding this out! @archerbroler 

Regardless of the full CPU case or not, ops.dispatch() will call `consume_task()` with a `cpu` id. The `consume_task()` will consume on the CPU's associated DSQ using `scx_bpf_consume()`. The `scx_bpf_consume()` will iterate the given DSQ and test if a task is runnable on the CPU (`task_can_run_on_remote_rq()`). So there is no such case.

If I am missing anything, please let me know.

**Comment by archerbroler** [comment]
Yes ,you are right. Sorry for my misunderstanding.

**Comment by multics69** [comment]
No problem. Actually, your comments help to find one more optimization in the dispatch path in this PR, https://github.com/sched-ext/scx/pull/872.
