### ISSUE TITLE
scx_lavd: Lock-related tracepoints do not exist for all kernel configurations

### ISSUE THREAD

**Issue by etsal** [sched-ext/scx#879]
The ```scx_lavd``` scheduler includes tracepoints in ```bpf/lock.bpf.c``` for ```mutex_lock``` and associated kernel functions. However, these are not always actual symbols in the kernel. For example, when using the CONFIG_DEBUG_LOCK_ALLOC option ```mutex_lock``` is a ```#define``` wrapper around ```mutex_lock_nested```.  This is a potential cause of the CI failures we are seeing:

1) [The error we have been seeing in the CI](https://github.com/sched-ext/scx/actions/runs/11633429989/job/32398585809#step:18:9708). Loading the scheduler fails because the tracepoint does not exit.
2) [Changing the tracepoint to point to ```mutex_lock_nested``` succeeds.](https://github.com/sched-ext/scx/actions/runs/11636686924/job/32408554918)

Is it possible to determine whether the symbol actually exists in the running kernel and adjust the tracepoint names at scx compile time? I do not think we can merge anything like  #878 because then that would break the scheduler in non-debug kernels.

**Comment by multics69** [comment]
Thank you for checking this out. I also have been investigating the problem but still not able to identify the root cause of the problem.

**Comment by multics69** [comment]
Close as the PR https://github.com/sched-ext/scx/pull/885 is posted.
