### ISSUE TITLE
scx_lavd: cur_logical_clk update method make task tail latency high

### ISSUE THREAD

**Issue by archerbroler** [sched-ext/scx#893]
In advance_cur_logical_clk, the more task is enqueued, the slower cur_logical_clk will go. which make later task's deadline smaller. 
As in the comment, other can jump in the run queue. But this will make task's tail latency increase too much. 
I think the advance_cur_logical_clk should not be affected by nr_queued.

**Comment by multics69** [comment]
@archerbroler -- Thank you for finding this out!

Originally the current advancement mechanism is designed to handle the oversubscribed situation well.
Even though there are many other tasks running, latency-critical tasks which shorter deadline can chip in the time line.
It gives latency-critical tasks.

Later I added considering greedness of a task in the timeline calculation to further handle the oversubscribed situation better.

Maybe, this would be a double penalty for non-latency critical tasks.

If you have some experimental results, I am happy to revisit and change it if necessary.

**Comment by archerbroler** [comment]
This will only effect heavy load system with many tasks, which is hard to create stable environment for comparation.
Just close this issue until I can found such case.
