### ISSUE TITLE
scx_lavd: task is centralized to big core when run schbench

### ISSUE THREAD

**Issue by archerbroler** [sched-ext/scx#938]
schbench will launch the CPU core number threads to run heavy load. 
In find_proper_dsq, these load thread will always match the big core, which will cause the big core CPU usage up to 100%, but not the little core.
Starving consume will ease this, but which will still cause the schedule latency goes very high.

**Comment by multics69** [comment]
Thanks @archerbroler for reporting the issue. 
Could you share the exact schbench option you used so I can reproduce the problem?

**Comment by multics69** [comment]
For the schbench with the default option, lavd performs better than EEVDF (6.12) in my testing.
Also, LAVD utilizes all the cores (P and E).

#### Test machine
- 13th Gen Intel(R) Core(TM) i7-13700H

#### EEVDF
Wakeup Latencies percentiles (usec) runtime 30 (s) (93059 total samples)
          50.0th: 6          (36530 samples)
          90.0th: 246        (28028 samples)
        * 99.0th: 1858       (8373 samples)
          99.9th: 2300       (837 samples)
          min=1, max=2406
Request Latencies percentiles (usec) runtime 30 (s) (93267 total samples)
          50.0th: 5112       (27959 samples)
          90.0th: 10064      (37302 samples)
        * 99.0th: 22880      (8361 samples)
          99.9th: 42176      (840 samples)
          min=2425, max=72852
RPS percentiles (requests) runtime 30 (s) (31 total samples)
          20.0th: 2700       (7 samples)
        * 50.0th: 2740       (10 samples)
          90.0th: 3820       (11 samples)
          min=2661, max=3870
average rps: 3108.90


#### LAVD
Wakeup Latencies percentiles (usec) runtime 30 (s) (119723 total samples)
          50.0th: 4          (38169 samples)
          90.0th: 8          (43684 samples)
        * 99.0th: 382        (9567 samples)
          99.9th: 1150       (1078 samples)
          min=1, max=17211
Request Latencies percentiles (usec) runtime 30 (s) (119953 total samples)
          50.0th: 4776       (36109 samples)
          90.0th: 5528       (47415 samples)
        * 99.0th: 9424       (10705 samples)
          99.9th: 16368      (1077 samples)
          min=2444, max=74336
RPS percentiles (requests) runtime 30 (s) (31 total samples)
          20.0th: 3812       (8 samples)
        * 50.0th: 3916       (9 samples)
          90.0th: 4376       (11 samples)
          min=3771, max=4537
average rps: 3998.43

**Comment by multics69** [comment]
@archerbroler -- If you can share a specific schbench option which creates the performance problem, it will be super helpful.

**Comment by archerbroler** [comment]
I use the schbench default option. I don't have a E/P Intel CPU, I think that's because I am trying to run this on arm64, which have a big cluster migration cost(That's not common, my hardware is special ).
Perhaps cluster/numa migration is just not the case LAVD should consider.
I will close this and try some NUMA aware way.
Thanks for your responsing.

**Comment by archerbroler** [comment]
NUMA migration is super high cost, which should not happen too much.
Relying on task steal from other dsq may cause the task migration too often, the NUMA migration in fair.c will also cause data pingpong in many case.
I often do task binding for this like in k8s. 
So I think a problem not well solved in fair.c should not be considered too much in SCX in this early stage.  
Sorry I cannot answer your hardware question because of commercial problem.

**Comment by multics69** [comment]
Great! If you have any suggestions (or PR) for a new feature, please let me know.
Thanks always for great questions!

**Comment by multics69** [comment]
@archerbroler -- You might be interested in this. Load balancing is improved in LAVD. 

https://github.com/sched-ext/scx/pull/1000
