### ISSUE TITLE
Introduce `for_each_possible_cpu()` `for_each_online_cpu()` iterators

### ISSUE THREAD

**Issue by htejun** [sched-ext/scx#966]
Some schedulers still assume that all possible CPUs are consecutively allocated which is not true on some machines. sched_ext exposes `scx_bpf_nr_cpu_ids()`, `scx_bpf_get_possible_cpumask()` and `scx_bpf_get_online_cpumask()`. Provide helpers to cache the result and macros to iterate over them.

**Comment by abrehman94** [comment]
@htejun could you please review the implementation? 

Example use 
```
static inline void example_use() {
    int *cpu;

    for_each_possible_cpu(cpu){
        bpf_printk("Updated CPU %d is possible", *cpu);
    }

    for_each_online_cpu(cpu){
        bpf_printk("CPU %d is online", *cpu);
    }
}
```
