### ISSUE TITLE
Rust schedulers fail with Duplicate CORE ID 0 error message on a two socket server

### ISSUE THREAD

**Issue by abrehman94** [sched-ext/scx#989]
On commit c15d9ea, rust schedulers fail to run with following error message on two socket machine running Ubuntu 20.02. 

```
  21:23:21 [INFO] scx_bpfland 1.0.7-g0936414 x86_64-unknown-linux-gnu/debug SMT off
  thread 'main' panicked at scheds/rust/scx_bpfland/src/main.rs:261:36:
  called `Result::unwrap()` on an `Err` value: Duplicate CORE ID 0
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Setup:

* Linux Version: Linux v-021 6.11.0-rc1-scx1+ #6 SMP PREEMPT_DYNAMIC Mon Oct 14 12:34:19 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
* Machine: dual socket machine with 24 cores each socket - [Intel® Xeon® Platinum 8160 Processor](https://www.intel.com/content/www/us/en/products/sku/120501/intel-xeon-platinum-8160-processor-33m-cache-2-10-ghz/specifications.html)
* scx_bpfland: built from commit c15d9ea

**Comment by hodgesds** [comment]
Can you try after [d97119]https://github.com/sched-ext/scx/commit/d971196595dd4add1e0559a5d1bfb8d1474315f5), I think it should be resolved.

**Comment by abrehman94** [comment]
Yes it does. Thanks!
